import { StyleSheet } from 'react-native';

export const filterModalStyles = {
  container: 'px-5 py-4 pb-12',
  section: 'mb-6',
  lastSection: 'mb-8',
  sectionTitle: 'text-slate-600 font-body-semibold mb-3 ml-1',
  categoryScrollContent: StyleSheet.create({
    content: {
      gap: 10,
      paddingVertical: 4,
    },
  }).content,
  categoryItem: 'flex-row items-center px-4 py-2.5 rounded-full border',
  categorySelected: 'bg-primary-500/10 border-primary-500',
  categoryDefault: 'bg-white border-slate-200/70',
  categoryText: 'font-body-medium ml-2',
  categoryTextSelected: 'text-primary-500',
  categoryTextDefault: 'text-slate-600',
  gridContainer: 'flex-row flex-wrap gap-2.5',
  priceItem: 'w-[47%] px-4 py-3 rounded-2xl border',
  priceSelected: 'bg-primary-500/10 border-primary-500',
  priceDefault: 'bg-white border-slate-200/70',
  priceText: 'text-center font-body-medium',
  priceTextSelected: 'text-primary-500',
  priceTextDefault: 'text-slate-600',
  sortContainer: 'bg-white border border-slate-200/70 rounded-3xl overflow-hidden',
  sortItem: 'flex-row justify-between items-center px-5 py-4 border-b border-slate-100',
  sortSelected: 'bg-primary-500/5',
  noBorderBottom: 'border-b-0',
  sortLeft: 'flex-row items-center',
  sortText: 'font-body-medium ml-3',
  sortTextSelected: 'text-slate-900 font-body-bold',
  sortTextDefault: 'text-slate-600',
  footerRow: 'flex-row gap-3',
  flexOne: 'flex-1',
};
