export const appSkeletonStyles = {
  root: 'flex-1 bg-[#F1F6FD]',
  header: 'w-full px-5 pt-12 pb-4 bg-white border-b border-slate-100 shadow-sm',
  topRow: 'flex-row items-center justify-between mb-4',
  locationBox: 'flex-row items-center gap-2',
  locationIcon: 'w-8 h-8 rounded-full bg-slate-200 animate-pulse',
  locationTextCol: 'gap-1.5',
  locationLabel: 'w-24 h-3 rounded bg-slate-200 animate-pulse',
  locationTitle: 'w-36 h-4 rounded bg-slate-200 animate-pulse',
  avatarCircle: 'w-10 h-10 rounded-full bg-slate-200 animate-pulse',
  searchRow: 'flex-row items-center gap-3',
  searchBar: 'flex-1 h-12 rounded-2xl bg-slate-100 animate-pulse',
  filterButton: 'w-12 h-12 rounded-2xl bg-slate-200 animate-pulse',
  content: 'flex-1 px-5 pt-4 gap-5',
  heroBanner: 'w-full h-40 rounded-3xl bg-slate-200 animate-pulse shadow-sm',
  sectionTitle: 'w-40 h-5 rounded-lg bg-slate-200 animate-pulse mb-3',
  categoriesRow: 'flex-row items-center justify-between my-1',
  categoryCircle: 'w-16 h-16 rounded-2xl bg-slate-200 animate-pulse',
  cardRow: 'flex-row gap-4 mt-2',
  cardItem: 'flex-1 h-44 rounded-3xl bg-white p-3 border border-slate-100 shadow-sm gap-3',
  cardImage: 'w-full h-24 rounded-2xl bg-slate-200 animate-pulse',
  cardTitle: 'w-3/4 h-4 rounded bg-slate-200 animate-pulse',
  cardSub: 'w-1/2 h-3 rounded bg-slate-100 animate-pulse',
};
